image:
  repository: registry.damien-venant.ovh/markivio/markivio-graphql
  tag: 1.0.0
  pullPolicy: Always

imagePullSecrets:
  secretRef: regcrd

config:
  ASPNETCORE_ENVIRONMENT: "Production"
  MARKIVIO_AUTHORITY: "https://markivio.eu.auth0.com/"
  MARKIVIO_AUDIENCE: "https://localhost:8080/"
  MARKIVIO_AUTH_DOMAIN: "markivio.eu.auth0.com"
  MARKIVIO_AUTH_AUDIENCE: "https://localhost:8080/"
  RABBIT_MQ__HOST: "markivio-rabbitmq-prod"
  RABBIT_MQ__PORT: '5672'

secretRef: markivio-graphql-secret

service:
  name: http
  port: 8080

ingressRoute:
  enabled: true
  domain: "markivio.damien-venant.ovh"

autoscaling:
  enabled: false
  replicaCount: 2
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

ressource:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

livenessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 60
  periodSeconds: 30

readinessProbe:
  httpGet:
    path: /health
    port: 8080
  periodSeconds: 5

jobs:
  enabled: true
  restartPolicy: Never
  jobs: 
    - name: migrate
      args: ["migrate"]
