FROM mcr.microsoft.com/dotnet/sdk:9.0 AS builder

ARG COMPIL_MODE=Release

WORKDIR /build

COPY . .

RUN dotnet restore \
  && mkdir publish \
  && dotnet publish \
    --no-restore \
    --configuration $COMPIL_MODE \
    --output ./publish \
    ./Presentation/Markivio.GraphQl/Markivio.GraphQl.csproj

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runner

WORKDIR /app

COPY --from=builder /build/publish ./markivio

EXPOSE 8080
ENTRYPOINT ["./markivio/Markivio.GraphQl"]

