apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "deploy.fullname" . }}
  labels:
    {{- include "deploy.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "deploy.name" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ include "deploy.name" .}}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default 'latest' }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
          {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              valueFrom:
                configMapKeyRef:
                  name: {{ include "deploy.fullname" . }}-config
                  key: {{ $value.key }}
          {{- end }}
            - name: ConnectionStrings__markivio
              valueFrom:
                secretKeyRef:
                  name: {{ include "deploy.fullname" . }}-secret
                  key: connectionString
