{{- if .Values.jobs.enabled }}
{{- $root := . }}
{{- range .Values.jobs.jobs }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "deploy.fullname" $root }}-job-{{ .name }}-{{ $root.Chart.revision }}
  labels: 
    {{- include "deploy.labels" $root | nindent 4 }}
spec:
  template:
    spec:
      imagePullSecrets:
        - name: {{ $root.Values.imagePullSecrets.secretRef }}
      restartPolicy: {{ $root.Values.jobs.restartPolicy | default "Never" }}
      containers:
      - name: {{ .name | quote }}
        image: "{{ .image | default $root.Values.image.repository }}:{{ .tag | default $root.Values.image.tag }}"
        {{- with .command }}
        command: {{ . }}
        {{- end }}
        {{- with .args }}
        args: {{ . }}
        {{- end }}
        envFrom: 
        - configMapRef: 
            name: {{ include "deploy.fullname" $root }}-configmap
        - secretRef:
            name: {{ $root.Values.secretRef | quote }}
{{- end }}
{{- end }}
