// <auto-generated />
using System;
using System.Collections.Generic;
using Markivio.Persistence.Config;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Markivio.Persistence.Migrations
{
    [DbContext(typeof(MarkivioContext))]
    [Migration("20260421172423_RemoveTagJson")]
    partial class RemoveTagJson
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArticleTag", b =>
                {
                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uuid")
                        .HasColumnName("articleId");

                    b.Property<Guid>("TagsId")
                        .HasColumnType("uuid")
                        .HasColumnName("tagsId");

                    b.HasKey("ArticleId", "TagsId")
                        .HasName("pK_articleTag");

                    b.HasIndex("TagsId")
                        .HasDatabaseName("iX_articleTag_tagsId");

                    b.ToTable("articleTag", (string)null);
                });

            modelBuilder.Entity("Markivio.Domain.Entities.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<Guid?>("FolderId")
                        .HasColumnType("uuid")
                        .HasColumnName("folderId");

                    b.Property<bool>("IsFramable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isFramable");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userId");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ArticleContent", "Markivio.Domain.Entities.Article.ArticleContent#ArticleContent", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Content")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("articleContent_Content");

                            b1.Property<string>("Description")
                                .HasColumnType("text")
                                .HasColumnName("articleContent_Description");

                            b1.Property<string>("Source")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("articleContent_Source");
                        });

                    b.HasKey("Id")
                        .HasName("pK_articles");

                    b.HasIndex("FolderId")
                        .HasDatabaseName("iX_articles_folderId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("iX_articles_userId");

                    b.ToTable("articles", (string)null);
                });

            modelBuilder.Entity("Markivio.Domain.Entities.Folder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userId");

                    b.HasKey("Id")
                        .HasName("pK_folders");

                    b.HasIndex("UserId")
                        .HasDatabaseName("iX_folders_userId");

                    b.ToTable("folders", (string)null);
                });

            modelBuilder.Entity("Markivio.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userId");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "TagValue", "Markivio.Domain.Entities.Tag.TagValue#TagValueObject", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Color")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("tagValue_Color");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("tagValue_Name");
                        });

                    b.HasKey("Id")
                        .HasName("pK_tags");

                    b.HasIndex("UserId")
                        .HasDatabaseName("iX_tags_userId");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("Markivio.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("authId");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Email", "Markivio.Domain.Entities.User.Email#EmailValueObject", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("email_Email");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Identity", "Markivio.Domain.Entities.User.Identity#IdentityValueObject", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("identity_FirstName");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("identity_LastName");

                            b1.Property<string>("Username")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("identity_Username");
                        });

                    b.HasKey("Id")
                        .HasName("pK_users");

                    b.HasIndex("AuthId")
                        .HasDatabaseName("iX_users_authId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ArticleTag", b =>
                {
                    b.HasOne("Markivio.Domain.Entities.Article", null)
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_articleTag_articles_articleId");

                    b.HasOne("Markivio.Domain.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_articleTag_tag_tagsId");
                });

            modelBuilder.Entity("Markivio.Domain.Entities.Article", b =>
                {
                    b.HasOne("Markivio.Domain.Entities.Folder", "Folder")
                        .WithMany("Articles")
                        .HasForeignKey("FolderId")
                        .HasConstraintName("fK_articles_folder_folderId");

                    b.HasOne("Markivio.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_articles_user_userId");

                    b.Navigation("Folder");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Markivio.Domain.Entities.Folder", b =>
                {
                    b.HasOne("Markivio.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_folders_user_userId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Markivio.Domain.Entities.Tag", b =>
                {
                    b.HasOne("Markivio.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_tags_users_userId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Markivio.Domain.Entities.Folder", b =>
                {
                    b.Navigation("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
