// <auto-generated />
using System;
using Markivio.Persistence.Config;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Markivio.Persistence.Migrations
{
    [DbContext(typeof(MarkivioContext))]
    [Migration("20260312212719_AddTimeStamp")]
    partial class AddTimeStamp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Markivio.Domain.Entities.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<Guid?>("FolderId")
                        .HasColumnType("uuid")
                        .HasColumnName("folderId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userId");

                    b.HasKey("Id")
                        .HasName("pK_article");

                    b.HasIndex("FolderId")
                        .HasDatabaseName("iX_article_folderId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("iX_article_userId");

                    b.ToTable("article", (string)null);
                });

            modelBuilder.Entity("Markivio.Domain.Entities.Folder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userId");

                    b.HasKey("Id")
                        .HasName("pK_folder");

                    b.HasIndex("UserId")
                        .HasDatabaseName("iX_folder_userId");

                    b.ToTable("folder", (string)null);
                });

            modelBuilder.Entity("Markivio.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userId");

                    b.HasKey("Id")
                        .HasName("pK_tag");

                    b.HasIndex("UserId")
                        .HasDatabaseName("iX_tag_userId");

                    b.ToTable("tag", (string)null);
                });

            modelBuilder.Entity("Markivio.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("authId");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("firstName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("lastName");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pK_user");

                    b.HasIndex("AuthId")
                        .HasDatabaseName("iX_user_authId");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("Markivio.Domain.Entities.Article", b =>
                {
                    b.HasOne("Markivio.Domain.Entities.Folder", "Folder")
                        .WithMany("Articles")
                        .HasForeignKey("FolderId")
                        .HasConstraintName("fK_article_folder_folderId");

                    b.HasOne("Markivio.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_article_user_userId");

                    b.OwnsOne("Markivio.Domain.Entities.ArticleContent", "ArticleContent", b1 =>
                        {
                            b1.Property<Guid>("ArticleId");

                            b1.Property<string>("Content")
                                .IsRequired();

                            b1.Property<string>("Description");

                            b1.Property<string>("Source")
                                .IsRequired();

                            b1.HasKey("ArticleId");

                            b1.ToTable("article");

                            b1
                                .ToJson("articleContent")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ArticleId")
                                .HasConstraintName("fK_article_article_id");

                            b1.OwnsMany("Markivio.Domain.Entities.SoftTag", "Tags", b2 =>
                                {
                                    b2.Property<Guid>("ArticleContentArticleId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("Color")
                                        .IsRequired();

                                    b2.Property<string>("Name")
                                        .IsRequired();

                                    b2.HasKey("ArticleContentArticleId", "__synthesizedOrdinal")
                                        .HasName("pK_article");

                                    b2.ToTable("article");

                                    b2.WithOwner()
                                        .HasForeignKey("ArticleContentArticleId")
                                        .HasConstraintName("fK_article_article_ArticleContentArticleId");
                                });

                            b1.Navigation("Tags");
                        });

                    b.Navigation("ArticleContent")
                        .IsRequired();

                    b.Navigation("Folder");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Markivio.Domain.Entities.Folder", b =>
                {
                    b.HasOne("Markivio.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_folder_user_userId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Markivio.Domain.Entities.Tag", b =>
                {
                    b.HasOne("Markivio.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_tag_user_userId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Markivio.Domain.Entities.Folder", b =>
                {
                    b.Navigation("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
