// <auto-generated />
using System;
using System.Collections.Generic;
using Markivio.Persistence.Config;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Markivio.Persistence.Migrations
{
    [DbContext(typeof(MarkivioContext))]
    partial class MarkivioContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Markivio.Domain.Entities.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<Guid?>("FolderId")
                        .HasColumnType("uuid")
                        .HasColumnName("folderId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userId");

                    b.HasKey("Id")
                        .HasName("pK_articles");

                    b.HasIndex("FolderId")
                        .HasDatabaseName("iX_articles_folderId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("iX_articles_userId");

                    b.ToTable("articles", (string)null);
                });

            modelBuilder.Entity("Markivio.Domain.Entities.Folder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userId");

                    b.HasKey("Id")
                        .HasName("pK_folders");

                    b.HasIndex("UserId")
                        .HasDatabaseName("iX_folders_userId");

                    b.ToTable("folders", (string)null);
                });

            modelBuilder.Entity("Markivio.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userId");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "TagValue", "Markivio.Domain.Entities.Tag.TagValue#TagValueObject", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Color")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("tagValue_Color");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("tagValue_Name");
                        });

                    b.HasKey("Id")
                        .HasName("pK_tags");

                    b.HasIndex("UserId")
                        .HasDatabaseName("iX_tags_userId");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("Markivio.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("authId");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Email", "Markivio.Domain.Entities.User.Email#EmailValueObject", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("email_Email");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Identity", "Markivio.Domain.Entities.User.Identity#IdentityValueObject", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("identity_FirstName");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("identity_LastName");

                            b1.Property<string>("Username")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("identity_Username");
                        });

                    b.HasKey("Id")
                        .HasName("pK_users");

                    b.HasIndex("AuthId")
                        .HasDatabaseName("iX_users_authId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Markivio.Domain.Entities.Article", b =>
                {
                    b.HasOne("Markivio.Domain.Entities.Folder", "Folder")
                        .WithMany("Articles")
                        .HasForeignKey("FolderId")
                        .HasConstraintName("fK_articles_folder_folderId");

                    b.HasOne("Markivio.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_articles_user_userId");

                    b.OwnsOne("Markivio.Domain.Entities.ArticleContent", "ArticleContent", b1 =>
                        {
                            b1.Property<Guid>("ArticleId");

                            b1.Property<string>("Content")
                                .IsRequired();

                            b1.Property<string>("Description");

                            b1.Property<string>("Source")
                                .IsRequired();

                            b1.HasKey("ArticleId");

                            b1.ToTable("articles");

                            b1
                                .ToJson("articleContent")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ArticleId")
                                .HasConstraintName("fK_articles_articles_id");

                            b1.OwnsMany("Markivio.Domain.ValueObject.TagValueObject", "Tags", b2 =>
                                {
                                    b2.Property<Guid>("ArticleContentArticleId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("Color")
                                        .IsRequired();

                                    b2.Property<string>("Name")
                                        .IsRequired();

                                    b2.HasKey("ArticleContentArticleId", "__synthesizedOrdinal")
                                        .HasName("pK_articles");

                                    b2.ToTable("articles");

                                    b2.WithOwner()
                                        .HasForeignKey("ArticleContentArticleId")
                                        .HasConstraintName("fK_articles_articles_ArticleContentArticleId");
                                });

                            b1.Navigation("Tags");
                        });

                    b.Navigation("ArticleContent")
                        .IsRequired();

                    b.Navigation("Folder");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Markivio.Domain.Entities.Folder", b =>
                {
                    b.HasOne("Markivio.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_folders_user_userId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Markivio.Domain.Entities.Tag", b =>
                {
                    b.HasOne("Markivio.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_tags_users_userId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Markivio.Domain.Entities.Folder", b =>
                {
                    b.Navigation("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
