---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: markivio-worker-secret
  namespace: markivio-prod
spec:
  encryptedData:
    WORKER_MQ_PASSWORD: AgCTDVGRT6DaGxvl8iILS7+Y/PmMyRlJuDhUshpO0LLZMolWJdMXGqC5kFDY3R8lBQRdP8Z74XlTWbKrIC/x9ftjdKA5NiYH1c2VUeJ9qOkydQXHLSoGEbEJVqbXeI8+xHbKpBmXoZ+CGthniqlrCRgVlrTvxvU2S1d9kqsEY+eMaquxLSKmKs69AK5xOVz94DKJZmv0skZIxuzoQFe7JS7o5GUEMfll6frLQgPYps1QteCjuHAQjS4ib1qwecBVRsPEg/qikkG1Az5FmtEI+621w5kpGh7bOxS1tbVV1oT2TGy2EqA6QJyOGh7awKE7xDUCx88nWgPyz2VUEG4fdnT3zjpnDG7vTHhH7q7R6PbMUO0lrH03h2ZOtClecmzcKukLDwlmrT2YtnZ1emsT8GiX65/vK9TPC27EjNAwFf2OJt1nJXdjtdAIgG9hIn8F8yrx97m3OzRARPdfBvG1izCzhCxyTBxSoR+50U2CyBMbZN53iE79F6Tv6TPvgVse/nWA2ulR6hdYOD0HmsYhCmCTMlEmjGArGZDB//J1yiOhwiuNbP1RlWfXYpqs5GyKxd0sgjXp+9dYugcv7E/ivrLn+B9hiwTQedEWZKun2AWDLc2yFxPxhOzZ8M1X9yBM/kw/A81JgHO+eWjnizu++S9sQlEW/XcoLt17kRvpPkyo2c1HcX7zxr3nGHumRsywasJyQ40gksmoTtPfyLJyf3D3komVjwHIOZLwZyM9UaHNbQ==
    WORKER_PG_PASSWORD: AgCu3DBtLtyxTEfX5YbqsCS9eBwv01wh5oQfekOraa9Km8b/UDr4bwv2xkqboOFqMOCBbQftlWwGUydj+xOPmIf5s0LuJMnIW264URAnVGz3/tU7QQvCnJ/2y1kdnkEeUERJSAF+Q2tx0GwzVeHCkHlxlnSEcovICMp/2HrKOwnXDbwITF/dSEVtnOIJ4pUTus8wUqlfdUqHtbY9jxohlfWfnh63j8vNxIsAdkcvUfqOPO+OmmNvv6aEDgshNtjQb6QIGdrMdhXn3XB2b90SP7r3l67AM8R5MFMSywVscKuJzkzYIRRfbQHN6C6kHql8uXRyUyQEfekBgJSat9A9gpR4QwAJrwXVvfnUo3lFeBKFws/iWVkTAE2GW6Nld02K5vKLakY5fBNLEQnGHmL+yNQFPlfbf0GgGIHEbejIlvlaS/RnDihL+rIsgz+cKnaHndxWdEiRVnaMGtno25rl9zJpySrL8CBKlHliirDDKRaCGkY6DQHOVAgW0q2ftWCH+IQUE4RFR1GMjRbyJ7psQQ1XHzCkrmYRqh0YhrmFn677kH9rQLlkiaMr3dAQk+Vf6wVDsLnBO1nWmo2oeflCiWrcAFDRRvvRnHbXSrOsQ30pHWlhttJYWZ7bLvjfhSd+uJ7Zw1n5zZFBDyjx0oWuQ7g9XxCTQuwDWTDR6upflDHXvuPoPdUIRpvx7afVENrnWRfiRkCnWWzoTHQeFV371g==
  template:
    metadata:
      name: markivio-worker-secret
      namespace: markivio-prod
