---
name: build and test

on:
  pull_request:
    branches:
      - dev
      - main
  workflow_dispatch:
    

jobs:
  build-backend:
    uses: ./.github/workflows/build-test-backend.yml
    with:
      go-version: "1.26.3"
      dotnet-version: "10"

  build-frontend:
    uses: ./.github/workflows/build-test-frontend.yml
    with:
      node-version: 22.17.0
